### ISSUE TITLE
Crashes when no Internet connection is available

### ISSUE THREAD

**Issue by probonopd** [mike-engel/Barnacal#2]
Crashes when no Internet connection is available. Should show a message instead.

```
raven@2.1.2 alert: failed to send exception to sentry: getaddrinfo ENOTFOUND sentry.io sentry.io:443
TypeError: Error processing argument at index 0, conversion failure from /run/firejail/appimage/.appimage-6982/usr/bin/resources/app.asar/Design/icons/tray/BarnacalIcon3Template@2x.png
    at App.<anonymous> (/run/firejail/appimage/.appimage-6982/usr/bin/resources/app.asar/index.js:96:14)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:194:7
Parent pid 6982, child pid 6985
```

Reference:
https://travis-ci.org/AppImage/appimage.github.io/builds/271349341#L758-L763

**Comment by mike-engel** [comment]
Thanks! If you're offline, it won't report to sentry anymore.
